import type { ViolationBundle } from './types.js';

/**
 * Generate social media payloads — thread-ready posts for X/LinkedIn.
 */
export function generateSocialPayload(bundle: ViolationBundle): string {
  var v = bundle.violation;
  var destinations = new Set(bundle.evidence.map(function(e) { return e.request_destination; }));
  var destCount = destinations.size;

  var lines: string[] = [];

  lines.push('# SOCIAL MEDIA PAYLOAD');
  lines.push('');
  lines.push('---');
  lines.push('');

  // X/Twitter thread
  lines.push('## X/Twitter Thread');
  lines.push('');

  lines.push('### Post 1 (Hook)');
  lines.push('');
  if (v.violation_type === 'preconsent_marketing_transfer') {
    lines.push(v.site_domain + ' says they respect your privacy.');
    lines.push('');
    lines.push('Our data shows they send your information to ' + destCount +
      ' marketing tracker' + (destCount > 1 ? 's' : '') + ' BEFORE you ever see a consent banner.');
    lines.push('');
    lines.push(v.evidence_count + ' documented violations. Thread:');
  } else {
    lines.push('Your browser told ' + v.site_domain + ' not to sell your data (via Global Privacy Control).');
    lines.push('');
    lines.push('They ignored it and sent your data to ' + destCount + ' marketing service' +
      (destCount > 1 ? 's' : '') + ' anyway.');
    lines.push('');
    lines.push("Here's the evidence:");
  }
  lines.push('');

  lines.push('### Post 2 (Evidence)');
  lines.push('');
  lines.push('We detected these third-party trackers firing before any consent interaction:');
  lines.push('');
  destinations.forEach(function(d) {
    lines.push('- ' + d);
  });
  lines.push('');
  lines.push('Each request is timestamped, hashed, and part of a tamper-evident audit trail.');
  lines.push('');

  lines.push('### Post 3 (Impact)');
  lines.push('');
  if (v.estimated_users) {
    lines.push('Estimated ' + formatNumber(v.estimated_users) + ' users affected monthly.');
    lines.push('');
  }
  lines.push('Comparable enforcement actions:');
  lines.push('- GoodRx: $25M (FTC)');
  lines.push('- Sephora: $1.2M (CCPA)');
  lines.push('- BetterHelp: $7.8M (FTC)');
  lines.push('');

  lines.push('### Post 4 (CTA)');
  lines.push('');
  lines.push('Full evidence record: https://violationindex.com');
  lines.push('');
  lines.push('The clock is ticking. ' + v.site_domain + ' has 72 hours to respond.');
  lines.push('');
  lines.push('Fix it, dispute it, or let silence become the record.');
  lines.push('');

  lines.push('---');
  lines.push('');

  // LinkedIn post
  lines.push('## LinkedIn Post');
  lines.push('');
  if (v.violation_type === 'preconsent_marketing_transfer') {
    lines.push('Privacy policies mean nothing if the code contradicts them.');
    lines.push('');
    lines.push('We documented ' + v.evidence_count + ' instances of ' + v.site_domain +
      ' transferring user data to ' + destCount + ' marketing services before any consent banner was shown or interacted with.');
  } else {
    lines.push('Global Privacy Control (GPC) is a legally binding opt-out signal under CCPA/CPRA.');
    lines.push('');
    lines.push('We documented ' + v.site_domain + ' ignoring this signal and continuing to transfer user data to ' +
      destCount + ' marketing services.');
  }
  lines.push('');
  lines.push('Every evidence record is timestamped, SHA-256 hashed, and part of a tamper-evident chain of custody.');
  lines.push('');
  lines.push('Full record: https://violationindex.com');
  lines.push('');
  lines.push('#privacy #dataprotection #CCPA #GDPR #compliance');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('*Generated by Violation Index*');

  return lines.join('\n');
}

function formatNumber(n: number | null): string {
  if (!n) return '0';
  if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M';
  if (n >= 1000) return (n / 1000).toFixed(0) + 'K';
  return String(n);
}
